import React from "react";

const Payouts = () => {
  return (
    <div className="flex-[8] p-6">
      <p >Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel delectus, tempore suscipit hic voluptates consequuntur harum placeat dolorum ipsum aspernatur praesentium distinctio nemo omnis in eveniet similique necessitatibus fugit numquam enim culpa asperiores? Facilis repudiandae cum sint assumenda laudantium! Totam laborum sint molestias natus. Recusandae quasi voluptatum, fugiat ipsa voluptatibus repellat odit deleniti sunt esse sit inventore laborum quo. Ab laborum doloribus quas odit rem asperiores reprehenderit nobis ut minus non, accusamus molestiae? Enim voluptate libero repellendus hic error at, tenetur dolor quisquam officia adipisci accusamus, necessitatibus neque eaque culpa consectetur magnam et voluptas voluptates maxime delectus impedit ab. Praesentium fuga velit, accusamus eius quam quos id, error ducimus, modi voluptatum porro ut qui expedita. Aliquid voluptatibus odio explicabo pariatur, voluptates numquam debitis necessitatibus corrupti fuga. Molestias, minima, perferendis perspiciatis dolore explicabo porro eius maiores nulla soluta eum aliquam sed. Iusto cupiditate reiciendis illum similique impedit soluta pariatur, unde repellat mollitia eaque ratione voluptate corrupti inventore quam, sunt asperiores ipsum! Itaque iste inventore minus provident expedita accusamus vero omnis fugit? Cupiditate obcaecati magnam corrupti? Culpa molestiae totam inventore doloremque quasi ipsam nulla, ad quod saepe, accusamus ea beatae nam fugit tempore labore! Illo sed, temporibus id aliquam at officiis tempore vitae voluptas modi veniam! Libero explicabo pariatur provident, ducimus fuga iste commodi? Alias hic dolores, totam obcaecati quod nostrum numquam cupiditate ex debitis aspernatur veniam molestiae minus, ut facilis inventore eum consectetur delectus architecto corporis doloribus illum? Aperiam repudiandae fugiat dolorem debitis voluptates sint modi dolorum aut cupiditate ab quasi maiores, cum esse nesciunt, officia perspiciatis unde exercitationem nam officiis. Ipsam ut fugiat nam voluptatum tempore? Placeat eos facere ad reiciendis ullam asperiores dignissimos temporibus officiis quas necessitatibus dolores labore laudantium velit sunt fugiat, rerum sit architecto optio error unde quibusdam? Magnam nesciunt, provident esse saepe officiis laudantium soluta id.</p>
    </div>
  );
};

export default Payouts;
